services:
  web:
    image: ghcr.io/stassss2011/tristlabs-blazorwebapp:latest
    container_name: blazorwebapp
    restart: unless-stopped
    ports:
      - "80:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # watchtower має бачити registry credentials
      - /home/ubuntu/.docker/config.json:/config.json:ro
    command: --interval 30 --cleanup --label-enable